name: Github Actions in one repo to update a file in another repo when anything is commited on uat branch
on:
  push:
    branches:
      - 'uat'

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  push_and_deploy:
    name: Github Actions in one repo to update a file in another repo when anything is commited on uat branch
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: commit
        run: |
          git config --global user.email "darshan.gada@wohlig.com"
          git config --global user.name "darshanwohlig19"
          git clone https://darshanwohlig19:${{ secrets.TOKEN100 }}@github.com/darshanwohlig19/devops2.git
          cd manifest
