name: wohlig devops test

on:
  push:
    branches:
      - 'main'

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout test-commits
        uses: actions/checkout@v3
      - name: configure git
        run: |
          git config --global user.email "darshan.gada@wohlig.com"
          git config --global user.name "darshanwohlig19"
      - name: update file
        run: |
          echo "Updated content" > /devops2/blob/main/demo.txt

          git add devops2/demo.txt
          git commit -m "update new image"
 
          git status
 
          git push origin main
 
          git status
