name: Update File on Main Branch Commit
 
on:
  push:
    branches:
      - main
 
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
 
jobs:
  update-file:
    runs-on: ubuntu-latest
 
    steps:
      - name: checkout test-commits
        uses: actions/checkout@v3
      - name: commit
        run: |
          git clone https://darshanwohlig19:${{ secrets.TOKEN }}@github.com/darshanwohlig19/devops2.git
          cd devops2
          git config --global user.email "darshan.gada@wohlig.com"
          git config --global user.name "darshanwohlig19"
          cat demo.txt
          commit_count=$(grep -oP '(?<=commit count is : )\d+' demo.txt)
          new_commit_count=$((commit_count + 50))
          sed -i "s/commit count is : $commit_count/commit count is : $new_commit_count/" demo.txt
          echo "Commit count updated to: $new_commit_count"
          cat demo.txt
          git add .
          git remote set-url origin https://darshanwohlig19:${{ secrets.TOKEN }}@github.com/darshanwohlig19/devops2.git
          git commit -m "test"
          git push origin main
