name: Update File on Commit

on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  
jobs:
  updateFile:
    runs-on: ubuntu-latest-
    steps:
      - name: Checkout devops1 repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "darshan.gada@wohlig.com"
          git config --global user.name "darshanwohlig19"
          echo "https://darshanwohlig19:${{ secrets.TOKEN }}github.com/darshanwohlig19/devops2.git

      - name: Ensure demo.txt exists
        run: touch demo.txt

      - name: Increment commit count in devops2 repo
        run: |
          count=$(($(< demo.txt)+50))
          echo $count > demo.txt

      - name: Commit changes to devops2
        run: |
          git add .
          git commit -m "Increment commit count"
          git push origin main
