name: Build, Push, and Deploy
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: add_repo_and_change
        run: |
            git clone "https://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@github.com/darshanwohlig19/devops2.git"
            cd test-gitops
            git checkout main
            git config user.name "darshanwohlig19"
            git config user.email "darshan.gada@wohlig.com"
            commit_count=$(($(grep -oP 'my commit count is : \K\d+' text.txt) + 50))
            sed -i "s/my commit count is : [0-9]\+/my commit count is : $commit_count/" demo.txt
            cat demo.txt
            echo "my commit count is"
            git add . 
            git commit -m "change"
            git push origin main
