name: wohlig devops test

on:
  push:
    branches:
      - 'main'
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout test-commits
        uses: actions/checkout@v3
      - name: checkout test-gitops
        run: git clone https://darshanwohlig19:${{ secrets.TOKEN }}@github.com/darshanwohlig19/devops2.git
      - name: configure git
        run: |
          git config --global user.email "darshan.gada@wohlig.com"
          git config --global user.name "darshanwohlig19"
      - name: update file
        run: |
          cd devops2
          python3 demo.txt

          git add .
          git commit -m "update new image"
 
          git status
 
          git push --set-upstream origin main
 
          git status
