name: Update File on UAT Commit

on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change to repository directory
        run: cd devops2  # Replace 'file-to-update' with your repository's directory name if different

      - name: Update File
        run: |
          file="update.txt"
          count=$(grep -oP 'my commit count is: \K(\d+)' $file)
          new_count=$((count + 50))
          sed -i "s/my commit count is: $count/my commit count is: $new_count/" $file

      - name: Commit and Push Changes
        run: |
          git config --local user.email "darshan.gada@wohlig.com"
          git config --local user.name "darshanwohlig19"
          git add update.txt
          git commit -m "Increment commit count by 50"
          git push
